DROP TABLE TEST_INFO;
CREATE TABLE TEST_INFO (
SEQ                       		INTEGER PRIMARY KEY AUTOINCREMENT,
REG_NO                    		TEXT NOT NULL,
TEST_DATE_TIME            		TEXT NOT NULL,
NUMBER                    		INTEGER NOT NULL,
CABLE_TYPE						TEXT,
CABLE_DIAMETER					NUMERIC,
CABLE_MAJOR_AXIS				NUMERIC,
CABLE_MINOR_AXIS				NUMERIC,
TEST_PIECES_COUNT				INTEGER,
SERIAL_NO                 		TEXT,
CREATE_DT                 		TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
UPDATE_DT                 		TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);


DROP TABLE TEST_DATA;
CREATE TABLE TEST_DATA (
SEQ                       	INTEGER PRIMARY KEY AUTOINCREMENT,
TEST_INFO_SEQ             	INTEGER NOT NULL,
REG_NO                    	TEXT NOT NULL,
START_CHAMBER_TEMPERATURE	NUMERIC,
CHAMBER_TC					TEXT,
FAN_FLOWRATE				TEXT,
TRANSMISSION				TEXT,
ABSORBANCE					TEXT,
MAX_ABSORBANCE				TEXT,
MAX_ABSORBANCE0				TEXT,
MINIMUM_TRANSMISSION		NUMERIC,
MINIMUM_TRANSMISSION_SECOND INTEGER,
MAXIMUM_ABSORBANCE			NUMERIC,
FLAMEOUT_SECOND				TEXT,
TEST_DURATION				REAL,
SUMMARY_DESCRIPTION       	TEXT,
CREATE_DT                 	TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
UPDATE_DT                 	TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);


DROP TABLE QUALIFICATION_INFO;
CREATE TABLE QUALIFICATION_INFO (
SEQ                       		INTEGER PRIMARY KEY AUTOINCREMENT,
REG_NO                    		TEXT NOT NULL,
TEST_DATE_TIME            		TEXT NOT NULL,
TOLUENE_CONTENT           		NUMERIC,
TARGET_ABSORBANCE_MIN			NUMERIC.
TARGET_ABSORBANCE_MAX			NUMERIC.
SERIAL_NO                 		TEXT,
CREATE_DT                 		TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
UPDATE_DT                 		TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);


DROP TABLE QUALIFICATION_DATA;
CREATE TABLE QUALIFICATION_DATA (
SEQ                       	INTEGER PRIMARY KEY AUTOINCREMENT,
TEST_INFO_SEQ             	INTEGER NOT NULL,
REG_NO                    	TEXT NOT NULL,
START_CHAMBER_TEMPERATURE	NUMERIC,
CHAMBER_TC					TEXT,
FAN_FLOWRATE				TEXT,
TRANSMISSION				TEXT,
ABSORBANCE					TEXT,
MAX_ABSORBANCE				TEXT,
MAX_ABSORBANCE0				TEXT,
CORRECTED_ABSORBANCE		TEXT,
MINIMUM_TRANSMISSION		NUMERIC,
MINIMUM_TRANSMISSION_SECOND INTEGER,
MAXIMUM_ABSORBANCE			NUMERIC,
FLAMEOUT_SECOND				TEXT,
TEST_DURATION				REAL,
SUMMARY_DESCRIPTION       	TEXT,
CREATE_DT                 	TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
UPDATE_DT                 	TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);