DROP TABLE REGIST_INFO;
CREATE TABLE REGIST_INFO (
	SEQ							INTEGER PRIMARY KEY AUTOINCREMENT,
	REG_NO						TEXT NOT NULL,
	REG_DATE					TEXT NOT NULL,
	REG_ORDER					INTEGER NOT NULL,
	CUST_NO						TEXT,
	SPONSOR_NAME				TEXT,
	SPONSOR_ADDR				TEXT,
	SUPPLIER_NAME				TEXT,
	SUPPLIER_ADDR				TEXT,
	PRODUCT_NAME				TEXT,
	PRODUCT_DESC				TEXT,
	MANAGER_NAME				TEXT,
	OPERATOR_NAME				TEXT,
	USE_SPECIMEN_CONDITION		TEXT,
	CONDITION_TEMPERATURE		TEXT,
	CONDITION_HUMIDITY			TEXT,	
	CABLE_TYPE					TEXT,
	CABLE_DESC					TEXT,
	CABLE_DIAMETER				NUMERIC,
	CABLE_MAJOR_AXIS			NUMERIC,
	CABLE_MINOR_AXIS			NUMERIC,
	TEST_PIECES_COUNT			INTEGER,
	STATUS						TEXT NOT NULL,
	CREATE_DT					TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	UPDATE_DT					TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);


DROP TABLE QUALIFICATION_REGIST_INFO;
CREATE TABLE QUALIFICATION_REGIST_INFO (
	SEQ							INTEGER PRIMARY KEY AUTOINCREMENT,
	REG_NO						TEXT NOT NULL,
	REG_DATE					TEXT NOT NULL,
	REG_ORDER					INTEGER NOT NULL,
	USE_SPECIMEN_CONDITION		TEXT,
	CONDITION_TEMPERATURE		TEXT,
	CONDITION_HUMIDITY			TEXT,	
	TOLUENE_CONTENT				TEXT,
	CABLE_DESC					TEXT,
	STATUS						TEXT NOT NULL,
	CREATE_DT					TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	UPDATE_DT					TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);