DROP TABLE CONFIG_SETTING;
CREATE TABLE CONFIG_SETTING (
	KEY				TEXT NOT NULL,
	VALUE			TEXT NOT NULL,
	DESC			TEXT,
	DISPLAY_INDEX 	INTEGER,
	CREATE_DT		TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	UPDATE_DT		TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	PRIMARY KEY(KEY)
);

DELETE FROM CONFIG_SETTING;
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('LANGUAGE', 'ENG', '디스플레이 언어', 1);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('LABORATORY', '', '시험기관명', 2);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('LAB_ADDRESS', '', '시험기관 주소', 3);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('OPERATOR', '홍길동', '시험자', 4);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('MANAGER', '', '관리자', 5);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('REPORT_PATH', 'C:\DownLoad', 'Report 파일 저장위치', 6);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('SCREENSHOT_PATH', 'C:\DownLoad', 'ScreenShot 파일 저장위치', 7);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('EMPTY_LOGO', 'N', '로고 이미지 표시 여부(Y/N)', 8);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('LOGO_NAME', '', '로고 이미지 파일명', 9);

INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TITLE', 'IEC 61034', 'IEC 61034', 10);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_FAN_SPEED', '11', 'FAN SPEED', 11);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TEMPERATURE_MIN', '20', 'CHAMBER MINIMUM TEMPERATURE', 12);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TEMPERATURE_MAX', '30', 'CHAMBER MAXIMUM TEMPERATURE', 13);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_MAX_TEST_DURATION', '40', 'MAXIMUM TEST DURATION', 14);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_CHAMBER_VOLUME', '27', 'CHAMBER VOLUME', 15);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_LIGHT_PATH', '3', 'LIGHT PATH', 16);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TOLUENE_4_ABSORBANCE_MIN', '0.18', 'TOLUENE 4% MINIMUM ABSORBANCE', 17);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TOLUENE_4_ABSORBANCE_MAX', '0.26', 'TOLUENE 4% MAXIMUM ABSORBANCE', 18);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TOLUENE_10_ABSORBANCE_MIN', '0.80', 'TOLUENE 4% MINIMUM ABSORBANCE', 19);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('IEC61034_TOLUENE_10_ABSORBANCE_MAX', '1.20', 'TOLUENE 4% MAXIMUM ABSORBANCE', 20);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('ND_POLYNOMIAL', '1.20', 'TOLUENE 4% MAXIMUM ABSORBANCE ', 21);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('ND_1ST_TERM', '4', '', 22);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('ND_2ND_TERM', '1', '', 23);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('ND_3RD_TERM', '0', '', 24);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('ND_4TH_TERM', '0', '', 25);
INSERT INTO CONFIG_SETTING (KEY, VALUE, DESC, DISPLAY_INDEX) VALUES ('ND_INTERCEPT', '0', '', 26);

