DROP TABLE CHANNEL_SETTING;
CREATE TABLE CHANNEL_SETTING (
	CHANNEL				TEXT NOT NULL,
	ADDRESS				TEXT NOT NULL,
	MIN_VOLTAGE			NUMERIC NOT NULL,
	MAX_VOLTAGE			NUMERIC NOT NULL,
	GRADIENT_VOLTAGE	NUMERIC NOT NULL,
	INTERCEPT_VOLTAGE	NUMERIC NOT NULL,
	MIN_VALUE			NUMERIC NOT NULL,
	MAX_VALUE			NUMERIC NOT NULL,
	GRADIENT_VALUE		NUMERIC NOT NULL,
	INTERCEPT_VALUE		NUMERIC NOT NULL,
	DESC				TEXT,
	DISPLAY_INDEX		INTEGER,
	CREATE_DT			TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	UPDATE_DT			TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	PRIMARY KEY(CHANNEL)
);

DELETE FROM CHANNEL_SETTING;
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('AI_LIGHT_PHOTODIODE', 'Dev3/ai0', 0, 5, 6, 0, 0, 30, 1, 0, 'Light Photodiode', 1);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('AI_CHAMBER_TC', 'Dev3/ai1', 0, 5, 30, 0, 0, 150, 1, 0, 'Chamber Thermocouple', 2);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('AI_INVERTER', 'Dev3/ai2', 0, 5, 328, -270, -270, 1370, 1, 0, 'Inverter', 3);

INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('AO_INVERTER', 'Dev3/ao0', 0, 5, 6, 0, 0, 30, 1, 0, 'Inverter', 4);

INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_FILTER_CLEAR', 'Dev2/port0/line0', 0, 0, 0, 0, 0, 0, 1, 0, 'Clear Filter', 5);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_ND_FILTER_01', 'Dev2/port0/line1', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.1', 6);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_ND_FILTER_02', 'Dev2/port0/line2', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.2', 7);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_ND_FILTER_03', 'Dev2/port0/line3', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.3', 8);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_ND_FILTER_05', 'Dev2/port0/line4', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.5', 9);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_ND_FILTER_07', 'Dev2/port0/line5', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.7', 10);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_ND_FILTER_10', 'Dev2/port0/line6', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 1.0', 11);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_FILTER_DARK', 'Dev2/port0/line7', 0, 0, 0, 0, 0, 0, 1, 0, 'Dark Filter', 12);

INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_OUT_DAMPER', 'Dev2/port1/line0', 0, 0, 0, 0, 0, 0, 1, 0, 'Out Damper(Upper)', 13);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DI_IN_DAMPER', 'Dev2/port1/line1', 0, 0, 0, 0, 0, 0, 1, 0, 'In Damper(Lower)', 14);

INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_LIGHT', 'Dev2/port3/line0', 0, 0, 0, 0, 0, 0, 1, 0, 'Light', 15);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_IGNITOR', 'Dev2/port3/line1', 0, 0, 0, 0, 0, 0, 1, 0, 'Ignitor', 16);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_FAN', 'Dev2/port3/line2', 0, 0, 0, 0, 0, 0, 1, 0, 'Fan', 17);

INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_FILTER_CLEAR', 'Dev2/port2/line0', 0, 0, 0, 0, 0, 0, 1, 0, 'Clear Filter', 18);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_ND_FILTER_01', 'Dev2/port2/line1', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.1', 19);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_ND_FILTER_02', 'Dev2/port2/line2', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.2', 20);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_ND_FILTER_03', 'Dev2/port2/line3', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.3', 21);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_ND_FILTER_05', 'Dev2/port2/line4', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.5', 22);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_ND_FILTER_07', 'Dev2/port2/line5', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 0.7', 23);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_ND_FILTER_10', 'Dev2/port2/line6', 0, 0, 0, 0, 0, 0, 1, 0, 'ND Filter 1.0', 24);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_FILTER_DARK', 'Dev2/port2/line7', 0, 0, 0, 0, 0, 0, 1, 0, 'Dark Filter', 25);

INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_OUT_DAMPER', 'Dev2/port3/line3', 0, 0, 0, 0, 0, 0, 1, 0, 'Out Damper(Upper)', 26);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_IN_DAMPER', 'Dev2/port3/line4', 0, 0, 0, 0, 0, 0, 1, 0, 'In Damper(Lower)', 27);
INSERT INTO CHANNEL_SETTING (CHANNEL, ADDRESS, MIN_VOLTAGE, MAX_VOLTAGE, GRADIENT_VOLTAGE, INTERCEPT_VOLTAGE, MIN_VALUE, MAX_VALUE, GRADIENT_VALUE, INTERCEPT_VALUE, DESC, DISPLAY_INDEX) VALUES ('DO_LAMP', 'Dev2/port3/line5', 0, 0, 0, 0, 0, 0, 1, 0, 'Lamp', 28);
