DROP TABLE ND_FILTER;
CREATE TABLE ND_FILTER (
	FILTER_INDEX			INTEGER,
	FILTER_NO				TEXT,
	CALC_TRANSMISSION		NUMERIC,
	CERTI_TRANSMISSION		NUMERIC,
	MEASURE_TRANSMISSION	NUMERIC,
	ERROR_TRANSMISSION		NUMERIC,
	CREATE_DT				TIMESTAMP default (datetime('now', 'localtime')) NOT NULL,
	UPDATE_DT				TIMESTAMP default (datetime('now', 'localtime')) NOT NULL
);

DELETE FROM ND_FILTER;
INSERT INTO ND_FILTER (FILTER_INDEX, FILTER_NO, CALC_TRANSMISSION, CERTI_TRANSMISSION) VALUES (1, '0.1', 79.433, 79);
INSERT INTO ND_FILTER (FILTER_INDEX, FILTER_NO, CALC_TRANSMISSION, CERTI_TRANSMISSION) VALUES (2, '0.2', 63.096, 62);
INSERT INTO ND_FILTER (FILTER_INDEX, FILTER_NO, CALC_TRANSMISSION, CERTI_TRANSMISSION) VALUES (3, '0.3', 50.119, 51);
INSERT INTO ND_FILTER (FILTER_INDEX, FILTER_NO, CALC_TRANSMISSION, CERTI_TRANSMISSION) VALUES (4, '0.5', 31.623, 30);
INSERT INTO ND_FILTER (FILTER_INDEX, FILTER_NO, CALC_TRANSMISSION, CERTI_TRANSMISSION) VALUES (5, '0.7', 19.953, 20);
INSERT INTO ND_FILTER (FILTER_INDEX, FILTER_NO, CALC_TRANSMISSION, CERTI_TRANSMISSION) VALUES (6, '1.0', 10.000, 9);
